apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    author: vale
    type: redis_db
spec:
  replicas: 1
  selector:
    matchLabels:
      type: redis_db
  template:
    metadata:
      name: redis-pod
      labels:
        author: vale
        type: redis_db
    spec:
      containers:
        - name: myredis
          image: redis